#########
#  OSD  #
#########

osd-font=Nata Sans
osd-font-size=40
osd-color=0.0/0.0/0.0/1.0
osd-outline-size=1.5
osd-outline-color=1.0/1.0/1.0/1.0
osd-blur=0.1
osd-align-x=center
osd-margin-y=50
osd-duration=3000
osd-scale-by-window=yes
script-opts=console-font_size=10

###########
# OSC/OSD #
###########

osc=no
osd-bar=yes
osd-font='Inter Tight Medium'
osd-font-size=30
osd-color='#CCFFFFFF'
osd-border-color='#DD322640'
osd-bar-align-y=-1
osd-border-size=2
osd-bar-h=1
osd-bar-w=60
