###########
# GPU API # 
###########
gpu-api=vulkan

##########
# Player #
##########
hr-seek-framedrop=no
no-resume-playback
border=no
msg-color=yes
msg-module=yes
autofit=85%x85%
cursor-autohide=100
deinterlace=no

###############
# Screenshots #
###############
screenshot-template="%x/Screens/Screenshot-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png
screenshot-png-compression=4
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes

#########
# Cache #
#########
gpu-shader-cache-dir=~~/cache/shaders
icc-cache-dir=~~/cache/icc
cache=yes
cache-secs=900
demuxer-readahead-secs=180
demuxer-max-back-bytes=150MiB
demuxer-max-bytes=300MiB
stream-buffer-size=64MiB
demuxer-seekable-cache=yes
stream-lavf-o=reconnect=1,reconnect_streamed=1,reconnect_delay_max=5

##################
# Core Rendering #
##################
profile=high-quality
hwdec=auto-copy
vo=gpu-next
vd-queue-enable=no
target-prim=auto
target-trc=auto
target-contrast=auto

# Deband
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4

# Dither
dither=fruit
dither-depth=auto
temporal-dither=yes
temporal-dither-period=1

# Scaling
scale=ewa_lanczos
cscale=lanczos
dscale=catmull_rom
scale-blur=0.981251
scale-antiring=0.7
cscale-antiring=0.7
dscale-antiring=0.7
sigmoid-upscaling=yes
linear-downscaling=no
correct-downscaling=yes

# Shaders
glsl-shader="~~/shaders/ravu-zoom-ar-r3-rgb.hook"
glsl-shader="~~/shaders/CfL_Prediction.glsl"

# Interpolation
video-sync=display-resample
interpolation=yes
tscale=sphinx
tscale-blur=0.6991556596428412
tscale-radius=1.05
tscale-clamp=0.0

# SDR / HDR
tone-mapping=bt.2446a
target-colorspace-hint=yes

############################## PROFILES ##############################

[sdr]
cscale=mitchell

[anime-sdr]
# Decoder Settings
hwdec=auto-copy
hr-seek-framedrop=no
video-latency-hacks=yes
mc=0
autosync=30

# Video Queue
vd-queue-enable=yes
vd-queue-max-bytes=512MiB
vd-queue-max-samples=35
vd-queue-max-secs=60

# Scaling
scale=ewa_lanczos
cscale=ewa_lanczos
scale-radius=3.2384
scale-blur=1.05

# Deband
deband-iterations=2
deband-threshold=45
deband-range=16
deband-grain=20

[default]

############################
# Protocol Specific Config #
############################

[protocol.http]
hls-bitrate=max
cache=yes
no-cache-pause

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http
