# This file is used to configure the audio

# ao=wasapi # use wasapi audio output on Windows output driver
# ao=pulse # use pulse audio output on Linux
audio-exclusive=no
audio-format=float  				# Better than s32 for modern systems
volume-max = 200                          # maximum volume in %, everything above 100 results in amplification
audio-stream-silence                    # fix audio popping on random seek
audio-file-auto = fuzzy                   # external audio doesn't has to match the file name exactly to autoload
audio-pitch-correction = yes              # automatically insert scaletempo when playing with higher speed

# Global audio filter chain
# af-append=@GLOBAL:lavfi=[loudnorm=I=-16:TP=-3:LRA=4,acompressor=threshold=0.0625:ratio=2.5:attack=50:release=300:makeup=1,highpass=f=80,lowpass=f=16000]